// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oehtfqdhdyydbbdemorm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9laHRmcWRoZHl5ZGJiZGVtb3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDc1NDIsImV4cCI6MjA2NDY4MzU0Mn0.cayP2NbJBassK2PcVMiIUZrEhHuEqT2nqz0JrxpQNOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);